### PR TITLE
Add storage-permission-request

### PR DESCRIPTION
**Pull request by jkrude**
### Current problem
- Wrong permission is checked when importing an image.
- A crash occurs after selecting a picture (instead of using the camera).
- This results in a crash in the nextcloud-android-app too. 

### Suggested solution 
- The suggested changes would check for permission and, if missing, ask for the `READ_EXTERNAL_STORAGE` permission.
- Similar to the style in [AuthentificatiorActivity](https://github.com/nextcloud/android/blob/6239e608ae35c7fcbd6799d48844b40d306b10f3/src/main/java/com/owncloud/android/authentication/AuthenticatorActivity.java#L1314-L1339) or [PermissionUtil](https://github.com/nextcloud/android/blob/master/src/main/java/com/owncloud/android/utils/PermissionUtil.java).
#### Notes
Alternatively the permission-check could happen in the nextloud-android-app too ( in `AuthentificatiorActivity`), because the same permission is needed anyway later on. However, a user who only wants to use the camera would not know what for.

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This was already done by me: https://github.com/blikoon/QRCodeScanner/pull/21

But unfortunately it is not yet merged in upstream :S

**Comment by jkrude** [comment]
My bad, I should have looked more closely.
Silly question but if it wasn't merged since 2018 and causes an obvious exception in the nextcloud-android-app should it not be considered to skip the original repo?

**Comment by tobiasKaminsky** [comment]
> should it not be considered to skip the original repo?

I assumed that original repo would merge it, as I created a PR there.
Then I forgot.
I will merge it then and include it in NC app.

**Comment by tobiasKaminsky** [comment]
I think this is done via https://github.com/tobiasKaminsky/QRCodeScanner/pull/5 or?

**Pull request closed without merging**
